### PR TITLE
Responsive masonry component

### PR DESCRIPTION
**Pull request by RossWebFS**
https://github.com/user-attachments/assets/0fb865ab-94fa-4064-94b1-678874edc18a

### CODE REVIEW

**Review by mhevyk — COMMENTED** [review]
Please align this to the same line
image

**Review by mhevyk — COMMENTED** [review]
I find making whole card a link a bad idea. For example user wants to select some text and he or she is not able to do so. Maybe you have some ideas to improve this? I'd like to change this behavior comparing to mockup

**Comment by RossWebFS** [comment]
One solution to this behavior could be creating an animation for the appearance of the link button when hovering over the image.

**Comment by RossWebFS** [comment]
Of course! Made the gap between user avatar and text bigger

image

**Review by mhevyk — APPROVED** [review]

**Pull request merged**
